name: climate_change_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - joblib
